backup:
  image: eeacms/volumesbackup
  volumes:
  - /:/rootfs:ro
  - /var/lib/docker:/var/lib/docker:ro
  - /etc/localtime:/etc/localtime:ro
  - /var/local/dockerbck:/backup:rw
  environment:
  - SCHEDULE=30 3 * * *
