backup:
  restart: always
  image: eeacms/volumesbackup:1.1
  volumes:
  - /:/rootfs:ro
  - /var/lib/docker:/var/lib/docker:ro
  - /etc/localtime:/etc/localtime:ro
  - /var/local/dockerbck:/backup:rw
  environment:
  - SCHEDULE=20 0 * * *
